title: Stratégia na Vybudovanie Majetku
description: Objavte profesionálne stratégie pokru a blackjacku
url: https://mibrutubru.github.io/Strategia-na-vybudovanie-majetku

# Build settings
markdown: kramdown
theme: jekyll-theme-primer

# Exclude SCSS files
sass:
  sass_dir: _sass
  style: compressed

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.jpeg"
  - "*.jpg"
  - "*.png"
